//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Data
    {
        public Nullable<double> CB { get; set; }
        public Nullable<double> HRV { get; set; }
        public bool isInputed { get; set; }
    }
}
