//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coefficient
    {
        public double CB { get; set; }
        public Nullable<double> Coef1 { get; set; }
        public Nullable<double> Coef2 { get; set; }
        public Nullable<double> Coef3 { get; set; }
        public Nullable<double> Coef4 { get; set; }
        public Nullable<double> Coef5 { get; set; }
        public Nullable<double> Coef6 { get; set; }
        public Nullable<double> Coef7 { get; set; }
        public Nullable<double> Coef8 { get; set; }
        public Nullable<double> Coef9 { get; set; }
    
        public virtual Inputed_Values Inputed_Values { get; set; }
    }
}
